apiVersion: v1
data:
  additional-scrape-configs.yaml: |
    - job_name: 'nodejs-app'
      static_configs:
        - targets: ['http://192.168.49.2:32000/']
kind: ConfigMap
metadata:
  annotations: {}
  name: additional-scrape-configs
  namespace: monitoring
