apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'nodeapp-service'
        scrape_interval: 5s
        static_configs:
          - targets: ['http://192.168.49.2:32000/']
kind: ConfigMap
metadata:
  annotations: {}
  name: prometheus-config
  namespace: monitoring
