addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.152
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: minikube
  targetRef:
    kind: Pod
    name: prometheus-prometheus-kube-prometheus-prometheus-0
    namespace: monitoring
    uid: b8ac867d-bd92-4544-bb9d-acdbf53e262a
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:00Z"
  generateName: prometheus-kube-prometheus-prometheus-
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.7.2
    chart: kube-prometheus-stack-61.7.2
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    heritage: Helm
    kubernetes.io/service-name: prometheus-kube-prometheus-prometheus
    release: prometheus
    self-monitor: "true"
  name: prometheus-kube-prometheus-prometheus-vjwpj
  namespace: monitoring
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: prometheus-kube-prometheus-prometheus
    uid: 199445ba-9d1f-4d36-aa23-f146ef1b722a
ports:
- appProtocol: http
  name: reloader-web
  port: 8080
  protocol: TCP
- name: http-web
  port: 9090
  protocol: TCP
