addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.155
  conditions:
    ready: true
    serving: true
    terminating: false
  hostname: alertmanager-prometheus-kube-prometheus-alertmanager-0
  nodeName: minikube
  targetRef:
    kind: Pod
    name: alertmanager-prometheus-kube-prometheus-alertmanager-0
    namespace: monitoring
    uid: 813974e7-386a-4b0f-b509-89ff4072d71e
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:01Z"
  generateName: alertmanager-operated-
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: alertmanager-operated
    managed-by: prometheus-operator
    operated-alertmanager: "true"
    service.kubernetes.io/headless: ""
  name: alertmanager-operated-vfhgd
  namespace: monitoring
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: alertmanager-operated
    uid: 31675531-9f55-454d-822f-3646f4910703
ports:
- name: http-web
  port: 9093
  protocol: TCP
- name: udp-mesh
  port: 9094
  protocol: UDP
- name: tcp-mesh
  port: 9094
  protocol: TCP
