addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.155
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: minikube
  targetRef:
    kind: Pod
    name: alertmanager-prometheus-kube-prometheus-alertmanager-0
    namespace: monitoring
    uid: 813974e7-386a-4b0f-b509-89ff4072d71e
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:00Z"
  generateName: prometheus-kube-prometheus-alertmanager-
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.7.2
    chart: kube-prometheus-stack-61.7.2
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    heritage: Helm
    kubernetes.io/service-name: prometheus-kube-prometheus-alertmanager
    release: prometheus
    self-monitor: "true"
  name: prometheus-kube-prometheus-alertmanager-8tdvs
  namespace: monitoring
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: prometheus-kube-prometheus-alertmanager
    uid: fed9e9d5-e0e9-498b-8c59-5c2b2eb8ec73
ports:
- appProtocol: http
  name: reloader-web
  port: 8080
  protocol: TCP
- name: http-web
  port: 9093
  protocol: TCP
