addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints: null
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T16:12:34Z"
  generateName: ingress-monitor-nginx-ingress-nginx-controller-
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-monitor-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: ingress-nginx-4.11.1
    kubernetes.io/service-name: ingress-monitor-nginx-ingress-nginx-controller
  name: ingress-monitor-nginx-ingress-nginx-controller-cbfch
  namespace: monitoring
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: ingress-monitor-nginx-ingress-nginx-controller
    uid: 139a4cac-3c36-460f-a35c-45695eff2bf0
ports: null
