apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:00Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.1.0
    helm.sh/chart: grafana-8.3.8
  name: prometheus-grafana
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.244.0.149
    nodeName: minikube
    targetRef:
      kind: Pod
      name: prometheus-grafana-648c7ff88d-swq8j
      namespace: monitoring
      uid: fd6a8a95-c718-4cc9-bb6e-136fa4fd6363
  ports:
  - name: http-web
    port: 3000
    protocol: TCP
