apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:00Z"
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.7.2
    chart: kube-prometheus-stack-61.7.2
    heritage: Helm
    release: prometheus
    self-monitor: "true"
  name: prometheus-kube-prometheus-prometheus
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.244.0.152
    nodeName: minikube
    targetRef:
      kind: Pod
      name: prometheus-prometheus-kube-prometheus-prometheus-0
      namespace: monitoring
      uid: b8ac867d-bd92-4544-bb9d-acdbf53e262a
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
  - appProtocol: http
    name: reloader-web
    port: 8080
    protocol: TCP
