apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:01Z"
  labels:
    managed-by: prometheus-operator
    operated-alertmanager: "true"
    service.kubernetes.io/headless: ""
  name: alertmanager-operated
  namespace: monitoring
subsets:
- addresses:
  - hostname: alertmanager-prometheus-kube-prometheus-alertmanager-0
    ip: 10.244.0.155
    nodeName: minikube
    targetRef:
      kind: Pod
      name: alertmanager-prometheus-kube-prometheus-alertmanager-0
      namespace: monitoring
      uid: 813974e7-386a-4b0f-b509-89ff4072d71e
  ports:
  - name: udp-mesh
    port: 9094
    protocol: UDP
  - name: tcp-mesh
    port: 9094
    protocol: TCP
  - name: http-web
    port: 9093
    protocol: TCP
