apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T16:12:34Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-monitor-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
    helm.sh/chart: ingress-nginx-4.11.1
  name: ingress-monitor-nginx-ingress-nginx-controller
  namespace: monitoring
