apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:00Z"
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.7.2
    chart: kube-prometheus-stack-61.7.2
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-operator
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.244.0.151
    nodeName: minikube
    targetRef:
      kind: Pod
      name: prometheus-kube-prometheus-operator-597f45494f-zlscx
      namespace: monitoring
      uid: f1c9d3b3-e999-4480-a0e3-a0f47e2a41ef
  ports:
  - name: https
    port: 10250
    protocol: TCP
