apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:00:01Z"
  labels:
    managed-by: prometheus-operator
    operated-prometheus: "true"
    service.kubernetes.io/headless: ""
  name: prometheus-operated
  namespace: monitoring
subsets:
- addresses:
  - hostname: prometheus-prometheus-kube-prometheus-prometheus-0
    ip: 10.244.0.152
    nodeName: minikube
    targetRef:
      kind: Pod
      name: prometheus-prometheus-kube-prometheus-prometheus-0
      namespace: monitoring
      uid: b8ac867d-bd92-4544-bb9d-acdbf53e262a
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
