apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-11T16:05:54Z"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.13.0
    helm.sh/chart: kube-state-metrics-5.25.1
    release: prometheus
  name: prometheus-kube-state-metrics
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.244.0.150
    nodeName: minikube
    targetRef:
      kind: Pod
      name: prometheus-kube-state-metrics-688d66b5b8-f2bsm
      namespace: monitoring
      uid: 6d11f15d-abd0-4e6e-93a0-93c997bb9930
  ports:
  - name: http
    port: 8080
    protocol: TCP
