apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: ingress-monitor-nginx
      meta.helm.sh/release-namespace: monitoring
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-monitor-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.11.1
      helm.sh/chart: ingress-nginx-4.11.1
    name: ingress-monitor-nginx-ingress-nginx
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ingress-monitor-nginx-ingress-nginx
  subjects:
  - kind: ServiceAccount
    name: ingress-monitor-nginx-ingress-nginx
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: keda
      meta.helm.sh/release-namespace: monitoring
    labels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: keda
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: keda-operator-certs
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.15.0
      helm.sh/chart: keda-2.15.0
    name: keda-operator-certs
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: keda-operator-certs
  subjects:
  - kind: ServiceAccount
    name: keda-operator
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: prometheus
      meta.helm.sh/release-namespace: monitoring
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 11.1.0
      helm.sh/chart: grafana-8.3.8
    name: prometheus-grafana
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-grafana
  subjects:
  - kind: ServiceAccount
    name: prometheus-grafana
    namespace: monitoring
kind: RoleBindingList
