apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-monitor-nginx
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-monitor-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
    helm.sh/chart: ingress-nginx-4.11.1
  name: ingress-monitor-nginx-ingress-nginx
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-monitor-nginx-ingress-nginx
subjects:
- kind: ServiceAccount
  name: ingress-monitor-nginx-ingress-nginx
  namespace: monitoring
