apiVersion: v1
data:
  web-config.yaml: ""
kind: Secret
metadata:
  labels:
    managed-by: prometheus-operator
  name: alertmanager-prometheus-kube-prometheus-alertmanager-web-config
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: prometheus-kube-prometheus-alertmanager
    uid: 73e8987a-5d71-4ec1-995f-e6dc3bdaf7e1
type: Opaque
