apiVersion: v1
kind: Secret
metadata:
  labels:
    managed-by: prometheus-operator
  name: alertmanager-prometheus-kube-prometheus-alertmanager-tls-assets-0
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: prometheus-kube-prometheus-alertmanager
    uid: 73e8987a-5d71-4ec1-995f-e6dc3bdaf7e1
type: Opaque
