apiVersion: v1
kind: Service
metadata:
  labels:
    managed-by: prometheus-operator
    operated-alertmanager: "true"
  name: alertmanager-operated
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    name: prometheus-kube-prometheus-alertmanager
    uid: 73e8987a-5d71-4ec1-995f-e6dc3bdaf7e1
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9093
    protocol: TCP
    targetPort: http-web
  - name: tcp-mesh
    port: 9094
    protocol: TCP
    targetPort: 9094
  - name: udp-mesh
    port: 9094
    protocol: UDP
    targetPort: 9094
  selector:
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
