asLists: true
clearTarget: true
excluded:
  fields:
  - [status]
  - [metadata, uid]
  - [metadata, selfLink]
  - [metadata, resourceVersion]
  - [metadata, creationTimestamp]
  - [metadata, generation]
  - [metadata, annotations, "kubectl.kubernetes.io/last-applied-configuration"]
  kindFields:
    Service:
    - [spec, clusterIP]
  kindByField:
