apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nodejs-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: nodeapp-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  # triggers:
  #   - type: cpu
  #     metadata:
  #       type: AverageValue
  #       value: "50"
