apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nodeapp-deployment
  namespace: default
spec:
  scaleTargetRef:
    name: 
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: AverageValue
      value: "50"