apiVersion: apps/v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: ingress-app
      meta.helm.sh/release-namespace: default
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.11.1
      helm.sh/chart: ingress-nginx-4.11.1
      pod-template-hash: 544f5dfc8f
    name: ingress-app-ingress-nginx-controller-544f5dfc8f
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: ingress-app-ingress-nginx-controller
      uid: abf85df5-21d8-46ac-9fb2-6d72e8f9f573
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: ingress-app
        app.kubernetes.io/name: ingress-nginx
        pod-template-hash: 544f5dfc8f
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ingress-app
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/part-of: ingress-nginx
          app.kubernetes.io/version: 1.11.1
          helm.sh/chart: ingress-nginx-4.11.1
          pod-template-hash: 544f5dfc8f
      spec:
        containers:
        - args:
          - /nginx-ingress-controller
          - --publish-service=$(POD_NAMESPACE)/ingress-app-ingress-nginx-controller
          - --election-id=ingress-app-ingress-nginx-leader
          - --controller-class=k8s.io/ingress-nginx
          - --ingress-class=nginx
          - --configmap=$(POD_NAMESPACE)/ingress-app-ingress-nginx-controller
          - --validating-webhook=:8443
          - --validating-webhook-certificate=/usr/local/certificates/cert
          - --validating-webhook-key=/usr/local/certificates/key
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: LD_PRELOAD
            value: /usr/local/lib/libmimalloc.so
          image: registry.k8s.io/ingress-nginx/controller:v1.11.1@sha256:e6439a12b52076965928e83b7b56aae6731231677b01e81818bce7fa5c60161a
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - /wait-shutdown
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: controller
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 10254
            name: metrics
            protocol: TCP
          - containerPort: 8443
            name: webhook
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/local/certificates/
            name: webhook-cert
            readOnly: true
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: ingress-app-ingress-nginx
        serviceAccountName: ingress-app-ingress-nginx
        terminationGracePeriodSeconds: 300
        volumes:
        - name: webhook-cert
          secret:
            defaultMode: 420
            secretName: ingress-app-ingress-nginx-admission
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    labels:
      app: ml-api
      pod-template-hash: 548d698969
    name: ml-api-deployment-548d698969
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: ml-api-deployment
      uid: 0ef818ea-ee96-4f9e-927c-8e832de292e5
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ml-api
        pod-template-hash: 548d698969
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ml-api
          pod-template-hash: 548d698969
      spec:
        containers:
        - env:
          - name: FLASK_ENV
            value: production
          image: shreyas2204/ml-api:latest
          imagePullPolicy: Always
          name: ml-api
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "7"
      deployment.kubernetes.io/max-replicas: "9"
      deployment.kubernetes.io/revision: "8"
    labels:
      app: nodeapp
      pod-template-hash: 5768865f95
    name: nodeapp-deployment-5768865f95
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 7
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 5768865f95
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:27:02+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 5768865f95
      spec:
        containers:
        - image: shreyas2204/my-node-app
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "7"
      deployment.kubernetes.io/max-replicas: "9"
      deployment.kubernetes.io/revision: "7"
    labels:
      app: nodeapp
      pod-template-hash: 5dbb54bfd
    name: nodeapp-deployment-5dbb54bfd
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 5dbb54bfd
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:20:31+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 5dbb54bfd
      spec:
        containers:
        - image: shreyas2204/my-node-app
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "7"
      deployment.kubernetes.io/max-replicas: "9"
      deployment.kubernetes.io/revision: "4"
    labels:
      app: nodeapp
      pod-template-hash: 5ffb6f79b
    name: nodeapp-deployment-5ffb6f79b
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 5ffb6f79b
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:13:18+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 5ffb6f79b
      spec:
        containers:
        - image: shreyas2204/my-node-app:latest
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "7"
      deployment.kubernetes.io/max-replicas: "9"
      deployment.kubernetes.io/revision: "1"
    labels:
      app: nodeapp
      pod-template-hash: 6cc654cb66
    name: nodeapp-deployment-6cc654cb66
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 6cc654cb66
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 6cc654cb66
      spec:
        containers:
        - image: shreyas2204/my-node-app
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "2"
    labels:
      app: nodeapp
      pod-template-hash: 6f75998bfc
    name: nodeapp-deployment-6f75998bfc
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 6f75998bfc
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:09:48+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 6f75998bfc
      spec:
        containers:
        - image: shreyas2204/my-node-app
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "7"
      deployment.kubernetes.io/max-replicas: "9"
      deployment.kubernetes.io/revision: "6"
    labels:
      app: nodeapp
      pod-template-hash: 7564645cd5
    name: nodeapp-deployment-7564645cd5
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 7564645cd5
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:20:31+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 7564645cd5
      spec:
        containers:
        - image: shreyas2204/my-node-app:latest
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "7"
      deployment.kubernetes.io/max-replicas: "9"
      deployment.kubernetes.io/revision: "5"
    labels:
      app: nodeapp
      pod-template-hash: 86d4c675d
    name: nodeapp-deployment-86d4c675d
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: 86d4c675d
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:17:56+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: 86d4c675d
      spec:
        containers:
        - image: shreyas2204/my-node-app:latest
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "4"
      deployment.kubernetes.io/max-replicas: "5"
      deployment.kubernetes.io/revision: "3"
    labels:
      app: nodeapp
      pod-template-hash: c55db597
    name: nodeapp-deployment-c55db597
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nodeapp-deployment
      uid: 2d381825-af5a-4a38-9afd-2449c9efff4d
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: nodeapp
        pod-template-hash: c55db597
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-22T22:13:18+05:30"
        creationTimestamp: null
        labels:
          app: nodeapp
          pod-template-hash: c55db597
      spec:
        containers:
        - image: shreyas2204/my-node-app
          imagePullPolicy: Always
          name: nodeserver
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: ReplicaSetList
