apiVersion: v1
items:
- apiVersion: v1
  data:
    additional-scrape-configs.yaml: |
      - job_name: 'nodejs-app'
        static_configs:
          - targets: ['http://192.168.49.2:32000/']
  kind: ConfigMap
  metadata:
    annotations: {}
    name: additional-scrape-configs
    namespace: default
- apiVersion: v1
  data:
    allow-snippet-annotations: "false"
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: ingress-app
      meta.helm.sh/release-namespace: default
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.11.1
      helm.sh/chart: ingress-nginx-4.11.1
    name: ingress-app-ingress-nginx-controller
    namespace: default
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI0MDgxMDE1NDEzM1oXDTM0MDgwOTE1NDEzM1owFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALrD
      2HIS/oKfL5Hg9smwLsZ6BC7Y4gGSgzWSFVC2BDF2LKmz/LPOKeFkmMppMbD0u1Kx
      u8WC6CvaJDeAKpiIRo3FPHjiR9McgmutKrMco1exVe5w4l5q7NfpQlw1riNAOJXD
      ic/S4M9G/1GPgwtm8mZxKkgEy/m3zSVya94yC1n5MOI9eW+oXZ1q8V1EPu95Qt+u
      eTfHtB5rMZxi4GPN2d9bxP3ovqnoyLsYppq47TTkEkB1BpjumZnER2m8huIT7JMv
      2iSPy0PpGSa6he5zF20HoPsKSBRHFno+naljDbkhnNcXBEybwh8orDKwUBa6DnJb
      MXQNnMhkLRKbK71I85kCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBRLPdTtwTHTYIVi/2SMop7OTB9l1jANBgkqhkiG9w0BAQsFAAOCAQEAiUnk+0Ry
      Ei7YrQOnHyOScetUdjUUT9TA4z76hLs5hCzKRZkDaYXpjU7wxMcV7IdQShP1UMVW
      o9m+niKWFfWN3CGveTxObaxWEcOdHmITWR+QoGET+iQMJn/KGme9SnkixLCywgDV
      ltAkb8fyxe7eqAjH/haIx/7BluojDYrU7673FYTywM/dEUmtkgZEk2Ci614oclF6
      qvbU3EZw4PphLeeKRIQYjQImps7vWI4kaNLvAk8jgZAjZV5NpCVh7A7RctDW+pVj
      IFw3QShYTUpd3jQUhR3oYGKb84Lx+EOSkKe7HdrjbQcPr6J/fTRmFsJJnUW0Yaj5
      orZdad7YR3i9YQ==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    name: kube-root-ca.crt
    namespace: default
kind: ConfigMapList
