addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.154
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: minikube
  targetRef:
    kind: Pod
    name: ingress-app-ingress-nginx-controller-544f5dfc8f-5mkc8
    namespace: default
    uid: 7c40e53c-3d60-45e9-b293-02edefe3f3d3
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-08T17:30:13Z"
  generateName: ingress-app-ingress-nginx-controller-admission-
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: ingress-nginx-4.11.1
    kubernetes.io/service-name: ingress-app-ingress-nginx-controller-admission
  name: ingress-app-ingress-nginx-controller-admission-8r88t
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: ingress-app-ingress-nginx-controller-admission
    uid: c7b1ce27-4292-4ad8-9ddc-96be7c6b2ff5
ports:
- appProtocol: https
  name: https-webhook
  port: 8443
  protocol: TCP
