apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: ml-api-service
  namespace: default
spec:
  clusterIP: 10.101.53.44
  clusterIPs:
  - 10.101.53.44
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ml-api
  sessionAffinity: None
  type: ClusterIP
