apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.flowcontrol.apiserver.k8s.io
spec:
  group: flowcontrol.apiserver.k8s.io
  groupPriorityMinimum: 16100
  version: v1
  versionPriority: 21
