apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  name: system-node-high
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 400
  priorityLevelConfiguration:
    name: node-high
  rules:
  - resourceRules:
    - apiGroups:
      - ""
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - nodes
      - nodes/status
      verbs:
      - '*'
    - apiGroups:
      - coordination.k8s.io
      namespaces:
      - '*'
      resources:
      - leases
      verbs:
      - '*'
    subjects:
    - group:
        name: system:nodes
      kind: Group
