apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  name: endpoint-controller
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 150
  priorityLevelConfiguration:
    name: workload-high
  rules:
  - resourceRules:
    - apiGroups:
      - ""
      namespaces:
      - '*'
      resources:
      - endpoints
      verbs:
      - get
      - create
      - update
    subjects:
    - kind: User
      user:
        name: system:kube-controller-manager
    - kind: ServiceAccount
      serviceAccount:
        name: endpoint-controller
        namespace: kube-system
    - kind: ServiceAccount
      serviceAccount:
        name: endpointslicemirroring-controller
        namespace: kube-system
