apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    kubernetes.io/metadata.name: ingress-nginx
  name: ingress-nginx
spec:
  finalizers:
  - kubernetes
