apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    labels:
      kubernetes.io/metadata.name: default
    name: default
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    labels:
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      kubernetes.io/metadata.name: ingress-nginx
    name: ingress-nginx
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    labels:
      kubernetes.io/metadata.name: kube-node-lease
    name: kube-node-lease
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    labels:
      kubernetes.io/metadata.name: kube-public
    name: kube-public
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    labels:
      kubernetes.io/metadata.name: kube-system
    name: kube-system
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    labels:
      kubernetes.io/metadata.name: monitoring
    name: monitoring
  spec:
    finalizers:
    - kubernetes
kind: NamespaceList
