apiVersion: scheduling.k8s.io/v1
items:
- apiVersion: scheduling.k8s.io/v1
  description: Used for system critical pods that must run in the cluster, but can
    be moved to another node if necessary.
  kind: PriorityClass
  metadata:
    annotations: {}
    name: system-cluster-critical
  preemptionPolicy: PreemptLowerPriority
  value: 2000000000
- apiVersion: scheduling.k8s.io/v1
  description: Used for system critical pods that must not be moved from their current
    node.
  kind: PriorityClass
  metadata:
    annotations: {}
    name: system-node-critical
  preemptionPolicy: PreemptLowerPriority
  value: 2000001000
kind: PriorityClassList
