apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1EZ3dNekV5TVRjd05Wb1hEVE0wTURnd01qRXlNVGN3TlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXdZCmxHaEFBaDVzMVVzeVl2Z2tFbjRMeDk1VjFxejd2OTE5QjBkSlUxUnNPSG5qMXYwd3JiOUNTNGdYVUxJbUpOd0sKSUdtMktrSUVyZ3JJc0ZnTzRJQVVrQlhyS2kwYWVJeXduc20zTi9vbWY3UUoweTFmUmxvdG15aHdDUWhVV1R6agpzanV2a3pjbzVYajBjeCtscisrNXBQdURYN0RjOGRtRWYxUzV1RWRXNXJXVjNKdUF5WlI5aTlhQmlERUdFaDdWClg1UTNHbERhMmllY1ZQWnRNU0lyNm4xWTJBUFBGK0RqdjZqRkFDMkg0R0w2SVkwNUpIMGhDalRTVkZpNnJZUGYKbkNPbE1FY2ROYWM2aTBacFhKbzFrN2NEZmN3bEJwcnBJQzBJTHpoY1VRQUNIRWtCajJSTFBsMGZHV25Ic1U1Mwp6UnNWMW9Ib1ZnUVRTeCswWHQ4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSVW5KWGhBRSsrSlJrMWl4WFlaNFhtQWNvSEZEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF3ZHA1Ym4zZQpBV2dlK2tkSDFZZ2F3eXlSbi9FY3kzT0VsbUlpRk13MjhvdVo5bG4xbUV3Z21MTHlZdS9WY3pmT21ETjVhZ0hCCmtVVFE3UFloV2Nnb0U1TmE5cGtFQ2o0bkZXd0QxTXBBTkRrNkczWmIwak5INGJpbDNFSHZxeTVNY29DNjFQK2sKZTVPRDZ2S2ExMDdwL05mV1lOUzN2QjJIaHIveXU4M0pYaDdFQTI0U3BBc3RDdStqVFpLOEFyTzdkNkVBM0lLdAptMjllbkpPU1N1YlM4b2M3Q2VCY05QaS9KT2hBbVNaYXBoWnQ3UHMwOFZzNzZlRkFVZEU4bTNYL2xzb1BldTNzCmtHM1JnRnh4ZlVxTGVEcmRKMkUrYmhMZXNhUS9ZWnZQZnlrME45Q2JjM2R4TzRvcW9GSHNhUndYa1BQNzJlbzkKdmhKZUVwazhIb0dKcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://control-plane.minikube.internal:8443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
