apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTI0MDgwMzEyMTcwNVoXDTM0MDgwMjEyMTcwNVowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMwY
    lGhAAh5s1UsyYvgkEn4Lx95V1qz7v919B0dJU1RsOHnj1v0wrb9CS4gXULImJNwK
    IGm2KkIErgrIsFgO4IAUkBXrKi0aeIywnsm3N/omf7QJ0y1fRlotmyhwCQhUWTzj
    sjuvkzco5Xj0cx+lr++5pPuDX7Dc8dmEf1S5uEdW5rWV3JuAyZR9i9aBiDEGEh7V
    X5Q3GlDa2iecVPZtMSIr6n1Y2APPF+Djv6jFAC2H4GL6IY05JH0hCjTSVFi6rYPf
    nCOlMEcdNac6i0ZpXJo1k7cDfcwlBprpIC0ILzhcUQACHEkBj2RLPl0fGWnHsU53
    zRsV1oHoVgQTSx+0Xt8CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBRUnJXhAE++JRk1ixXYZ4XmAcoHFDANBgkqhkiG9w0BAQsFAAOCAQEAwdp5bn3e
    AWge+kdH1YgawyyRn/Ecy3OElmIiFMw28ouZ9ln1mEwgmLLyYu/VczfOmDN5agHB
    kUTQ7PYhWcgoE5Na9pkECj4nFWwD1MpANDk6G3Zb0jNH4bil3EHvqy5McoC61P+k
    e5OD6vKa107p/NfWYNS3vB2Hhr/yu83JXh7EA24SpAstCu+jTZK8ArO7d6EA3IKt
    m29enJOSSubS8oc7CeBcNPi/JOhAmSZaphZt7Ps08Vs76eFAUdE8m3X/lsoPeu3s
    kG3RgFxxfUqLeDrdJ2E+bhLesaQ/YZvPfyk0N9Cbc3dxO4oqoFHsaRwXkPP72eo9
    vhJeEpk8HoGJqw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  name: kube-root-ca.crt
  namespace: kube-node-lease
