apiVersion: coordination.k8s.io/v1
items:
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    annotations: {}
    name: minikube
    namespace: kube-node-lease
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: minikube
      uid: 537e713e-a2ba-414a-b2d2-6f82b3366e92
  spec:
    holderIdentity: minikube
    leaseDurationSeconds: 40
    renewTime: "2024-08-22T18:56:28.530518Z"
kind: LeaseList
