apiVersion: v1
data:
  client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTI0MDgwMzEyMTcwNVoXDTM0MDgwMjEyMTcwNVowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMwY
    lGhAAh5s1UsyYvgkEn4Lx95V1qz7v919B0dJU1RsOHnj1v0wrb9CS4gXULImJNwK
    IGm2KkIErgrIsFgO4IAUkBXrKi0aeIywnsm3N/omf7QJ0y1fRlotmyhwCQhUWTzj
    sjuvkzco5Xj0cx+lr++5pPuDX7Dc8dmEf1S5uEdW5rWV3JuAyZR9i9aBiDEGEh7V
    X5Q3GlDa2iecVPZtMSIr6n1Y2APPF+Djv6jFAC2H4GL6IY05JH0hCjTSVFi6rYPf
    nCOlMEcdNac6i0ZpXJo1k7cDfcwlBprpIC0ILzhcUQACHEkBj2RLPl0fGWnHsU53
    zRsV1oHoVgQTSx+0Xt8CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBRUnJXhAE++JRk1ixXYZ4XmAcoHFDANBgkqhkiG9w0BAQsFAAOCAQEAwdp5bn3e
    AWge+kdH1YgawyyRn/Ecy3OElmIiFMw28ouZ9ln1mEwgmLLyYu/VczfOmDN5agHB
    kUTQ7PYhWcgoE5Na9pkECj4nFWwD1MpANDk6G3Zb0jNH4bil3EHvqy5McoC61P+k
    e5OD6vKa107p/NfWYNS3vB2Hhr/yu83JXh7EA24SpAstCu+jTZK8ArO7d6EA3IKt
    m29enJOSSubS8oc7CeBcNPi/JOhAmSZaphZt7Ps08Vs76eFAUdE8m3X/lsoPeu3s
    kG3RgFxxfUqLeDrdJ2E+bhLesaQ/YZvPfyk0N9Cbc3dxO4oqoFHsaRwXkPP72eo9
    vhJeEpk8HoGJqw==
    -----END CERTIFICATE-----
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIIDETCCAfmgAwIBAgIIStErJ062EqgwDQYJKoZIhvcNAQELBQAwGTEXMBUGA1UE
    AxMOZnJvbnQtcHJveHktY2EwHhcNMjQwODA4MTMwNTExWhcNMzQwODA2MTMxMDEx
    WjAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBALeitW/T10VBqwF5ZVsJtED8vL8s9h8ph9C+HEWaHDD8dahK
    VYSt1muQrm6bRmYyo2AJOdj4ljYNeAw4ucjnjp/IxF2ozVQGvDlX5c8y1eZG7iII
    5kyz1DRo0WoNNvPmeRoAvy2NWFzxDelbkU88yolOVDL7vnwa8+RNLeq+uKtccOFF
    FBs18XepsZFo40LBYFs1EUnN+v8nf3AUHEbTU7RYkBB4UAGOWR2VTlWT6aKC9OJA
    7aCehNYQESp5CKlfZXF+ONI7JbuTt/YIG68g1jp3rWFu5miJCBhvrGOZmuh3dfDI
    MQUkVz87SV9zmp+LQpfagCIDh+KPAItfA1xd12ECAwEAAaNdMFswDgYDVR0PAQH/
    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBF4IE4Wh+qp41xDK9Yl
    w5JJH65eMBkGA1UdEQQSMBCCDmZyb250LXByb3h5LWNhMA0GCSqGSIb3DQEBCwUA
    A4IBAQCiGWDP0Rl59d9gPC7tQSftSwnQrXFtsawiKGJ5WdSfIIXiiheYtqmKugK9
    lHflc+p9lvLGHep6VLy7F2MAiA5iNNHPUZs24KLegN3JYelSJG7Nwq+T6N+c417N
    FRge9OzDAmyC3gGwi7gYi9BhXDrJ8l4p8w7R8Vd62R15aQEXq39Jh3NyJ13G8S67
    bqIasHqAjSkHL0oJ49l0JSHUGUQnRq6uTPJ5qc8AVltVzmhXKO0a8P3jzj++CfyO
    hp32ooxyRIq6A8H9qP1o5BiRm0v1ofIk1iExWxka45QB6LKurCFilnJt1b64F5xc
    wJtJqRw3PkTr9QGBvXmJTFH4iI1W
    -----END CERTIFICATE-----
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
kind: ConfigMap
metadata:
  name: extension-apiserver-authentication
  namespace: kube-system
