addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.168.49.2
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: minikube
  targetRef:
    kind: Pod
    name: etcd-minikube
    namespace: kube-system
    uid: 2bc345d7-ba65-4530-9b37-a00bceb1db8f
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-10T11:31:43Z"
  generateName: prometheus-kube-prometheus-kube-etcd-
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.7.2
    chart: kube-prometheus-stack-61.7.2
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    heritage: Helm
    jobLabel: kube-etcd
    kubernetes.io/service-name: prometheus-kube-prometheus-kube-etcd
    release: prometheus
    service.kubernetes.io/headless: ""
  name: prometheus-kube-prometheus-kube-etcd-pzq8b
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: prometheus-kube-prometheus-kube-etcd
    uid: 8f6e858b-b72c-4f8e-9617-1605a9b858ea
ports:
- name: http-metrics
  port: 2381
  protocol: TCP
