apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
  name: prometheus-kube-prometheus-kubelet
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.49.2
    targetRef:
      kind: Node
      name: minikube
      uid: f9fe5e0a-ec7a-4ec2-90f9-a25cc3fdc836
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
  - name: http-metrics
    port: 10255
    protocol: TCP
  - name: cadvisor
    port: 4194
    protocol: TCP
