apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-08-11T16:06:15Z"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.244.0.148
    nodeName: minikube
    targetRef:
      kind: Pod
      name: coredns-7db6d8ff4d-tjqfq
      namespace: kube-system
      uid: cd306b39-aa42-4d33-a349-4d314cbf549c
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: metrics
    port: 9153
    protocol: TCP
